ballerina-platform/module-ballerinax-azure-cosmosdb

- .travis.yml
> The travis.yml file which is needed for checking the build was not updated to the latest version of ballerina.
> Update the travis.yml to check if the build is successful
> Update travis.yml file
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> To Update the travis.yml file

- .travis.yml
- Ballerina.toml
- Dependencies.toml
- Package.md
- README.md
- stream_implementer.bal
- tests/test.bal
> To migrate Azure Cosmos DB connector to  Ballerina version SLAlpha5.
> Provide the Azure Cosmos DB connector in the latest version of Ballerina version.
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> Migrate the code to Ballerina SLAlpha5
> Update the documentation.
> Testerina
> Ballerina SLAlpha 5
> JDK 11
> Ubuntu 20.04 LTS
> Migrate the code to SLAlpha 5

- .github/workflows/ci.yml
- .github/workflows/release.yml
- Ballerina.toml
- Dependencies.toml
- Package.md
- README.md
- management_endpoint.bal
- stream_implementer.bal
- utils.bal
>  Change workflow files to slalpha5
> Bump the connector version from 0.1.3 to 0.1.4 for the new release
> Fix typos in documentation files
> Bump Workflow versions and fix typos in documentation

- Ballerina.toml
- Dependencies.toml
- README.md
- client_endpoint.bal
- management_endpoint.bal
- types.bal
> The display annotations for Azure Cosmos DB connector is inconsistent
> $Subject
> [SL Alpha 5] Make display annotations for Cosmos DB connector consistant

- README.md
- cosmosdb/client_endpoint.bal
- cosmosdb/management_endpoint.bal
> The display annotations for Azure Cosmos DB connector is inconsistent
> $Subject
> Make display annotations for Cosmos DB connector consistant 

- cosmosdb/Dependencies.toml
- gradle.properties
Bump dependency versions to slbeta2
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> Bump dependency versions for Ballerina SLBeta2

- Package.md
- README.md
> Update the documentation for create document samples

- cosmosdb/Dependencies.toml
- gradle.properties
$title
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
JDK 11
Ballerina SLBeta3
> Bump dependency versions for Ballerina SLBeta3

- cosmosdb/Ballerina.toml
Update keyword `dev tools` -> `it operations` in Ballerina.toml
> Update keyword `dev tools` -> `it operations`

- .github/workflows/ci.yml
- .github/workflows/daily-build.yml
- .github/workflows/release.yml
- .github/workflows/weekly-build.yml
- README.md
Related https://github.com/ballerina-platform/ballerina-extended-library/issues/128
- Add slbeta4 migration changes
* Ballerina Version: Ballerina swan lake beta 4
* Operating System: Ubuntu (Linux)
* Java SDK: Java 11
> Update ballerina commands

- cosmosdb/client_endpoint.bal
Modify icon as per new requirements 
- Removed .svg icon and added .png icon
- Icon size 200 x 200 px 
- Mention the icon in `Ballerina.toml` so that Ballerina central will render the connector icon
Fixes https://github.com/ballerina-platform/ballerina-extended-library/issues/179
- Improved connector icon
N/A
N/A
> Modify icon path in client.bal

- README.md
- cosmosdb/Ballerina.toml
- cosmosdb/Dependencies.toml
- cosmosdb/Package.md
- gradle.properties
- Bump version to `2.1.0`
- Update Ballerina version to `SLBeta6` in Package.md 
- Regenerate Dependencies.toml with `SLBeta6`
- Add `distribution = "slbeta6"` in Ballerina.toml
> Prepare for 2.1.0 release with SLBeta6

- cosmosdb/Ballerina.toml
- cosmosdb/management_endpoint.bal
- cosmosdb/samples/admin-operations/container/container_operations.bal
- cosmosdb/samples/admin-operations/database/database_operations.bal
- cosmosdb/samples/admin-operations/offers/offer_operations.bal
- cosmosdb/samples/admin-operations/users-permissions/users_access_control.bal
- cosmosdb/samples/data-operations/documents/document_operations.bal
- cosmosdb/stream_implementer.bal
- cosmosdb/tests/test.bal
- cosmosdb/utils.bal
> Fix warnings for slbeta6 release

- cosmosdb/Dependencies.toml
- Re-generate Dependencies.toml with latest pack to update latest standard library versions
> Re-generate Dependencies.toml with latest pack

- cosmosdb/Ballerina.toml
- cosmosdb/Dependencies.toml
- cosmosdb/Package.md
- gradle.properties
Purpose
- Prepare for 2.2.0 release
> Prepare for 2.2.0 release

- .github/workflows/ci.yml
- .github/workflows/weekly-build.yml
Add code coverage information to the workflows
Fixes # ([issue](https://github.com/ballerina-platform/ballerina-extended-library/issues/271))
- Add code coverage information to the workflows
Tested in the CI workflow
* Ballerina Version: 2201.0.0
* Operating System: Ubuntu 20.04
* Java SDK: 11
> [2201.0.0] Add code coverage info to workflows

- cosmosdb/Module.md
- cosmosdb/samples/data-operations/documents/create_document.bal
- cosmosdb/samples/data-operations/documents/delete_document.bal
- cosmosdb/samples/data-operations/documents/document_operations.bal
- cosmosdb/samples/data-operations/documents/get_document.bal
- cosmosdb/samples/data-operations/documents/list_documents.bal
- cosmosdb/samples/data-operations/documents/query_document.bal
- cosmosdb/samples/data-operations/documents/replace_document.bal
Update samples and documentation
Related Pull Requests 
https://github.com/ballerina-platform/module-ballerinax-azure-cosmosdb/pull/51
> Update samples and documentation

- .github/workflows/ci.yml
- .github/workflows/daily-build.yml
- .github/workflows/release.yml
- .github/workflows/weekly-build.yml
> Update CI with java build

- .github/workflows/ci.yml
- .github/workflows/daily-build.yml
- .github/workflows/release.yml
- .github/workflows/weekly-build.yml
> Set java home path in CI builds

- .github/workflows/dev-stg-release.yml
- Use ballerina action master for release
> Use ballerina action master for release

- cosmosdb/Ballerina.toml
- cosmosdb/Package.md
- gradle.properties
> Update bal dist version to `2201.0.1`

- cosmosdb/Module.md
- cosmosdb/samples/data-operations/documents/create_document.bal
- cosmosdb/samples/data-operations/documents/document_operations.bal
- cosmosdb/samples/data-operations/documents/replace_document.bal
Fix same compile time error in 3 files
Fixes 
[ballerina-platform/ballerina-extended-library/issues/331](https://github.com/ballerina-platform/ballerina-extended-library/issues/331)
Fix a compile time error
* Ballerina Version: 2201.0.0
* Operating System: Windows 10
* Java SDK:  11
> Fix errors in sample codes which result in a compile time error

- cosmosdb-native/build.gradle
- cosmosdb/Ballerina.toml
Fix dependency conflicts warning
Fixes 
https://github.com/ballerina-platform/ballerina-extended-library/issues/317
Fix dependency conflicts warning
* Ballerina Version: 2201.0.0
* Operating System: Ubuntu
* Java SDK: 11
> [2201.0.0] Fix dependency conflicts warning

- cosmosdb-native/build.gradle
- cosmosdb/Ballerina.toml
- cosmosdb/Dependencies.toml
- gradle.properties
Fix dependency conflicts warning
Fixes 
https://github.com/ballerina-platform/ballerina-extended-library/issues/317
Fix dependency conflicts warning
* Ballerina Version: 2201.0.0
* Operating System: Ubuntu
* Java SDK: 11
> Fix dependency conflicts warning 

- .github/workflows/dev-stg-release.yml
- Use ballerina action master branch in dev release
> Update ballerina action version in dev release

- .github/workflows/ci.yml
- .github/workflows/weekly-build.yml
Add code lines coverage
Fixes 
https://github.com/ballerina-platform/ballerina-extended-library/issues/407
> Add test coverage lines

- .github/workflows/dev-stg-release.yml
- .github/workflows/release.yml
- cosmosdb-native/src/main/java/io/ballerinax/cosmosdb/RecordIteratorUtils.java
- cosmosdb/Ballerina.toml
- cosmosdb/Dependencies.toml
- cosmosdb/Package.md
- cosmosdb/iterator.bal
- cosmosdb/tests/test.bal
- gradle.properties
Fix record type in stream next response
Fixes # (issue)
https://github.com/ballerina-platform/ballerina-extended-library/issues/437
- Fix record type in stream next response
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> Fix record type in stream next response

- cosmosdb/types.bal
> Update http version

- README.md
- cosmosdb/Package.md
$Subject
Fixes # https://github.com/ballerina-platform/ballerina-extended-library/issues/474
> Update Slack channel occurrences with Discord

- cosmosdb/Ballerina.toml
- cosmosdb/Dependencies.toml
- cosmosdb/Package.md
- gradle.properties
$Subject
Fixes # https://github.com/ballerina-platform/ballerina-extended-library/issues/475
> Update to Ballerina version 2201.3.0

- cosmosdb-native/build.gradle
- cosmosdb/Ballerina.toml
> [2201.4.1] Exclude netty from the jar

- cosmosdb/Ballerina.toml
- Add reactor netty dependencies in Ballerina.toml
> [2201.4.1] Add reactor netty dependencies in Ballerina.toml

- cosmosdb/Ballerina.toml
> [2201.4.1] Add micrometer dependency

- cosmosdb-native/build.gradle
- Exclude micrometer from the jar
> [2201.4.1] Exclude micrometer from the jar

- cosmosdb/tests/test.bal
- cosmosdb/types.bal
- cosmosdb/utils.bal
- Fix https://github.com/wso2-enterprise/choreo/issues/20429
> [2201.4.x] Fix compile time warnings

- cosmosdb/Ballerina.toml
- cosmosdb/Dependencies.toml
- gradle.properties
- Bump connector version to `4.1.1`
> [2201.4.x] Bump connector version to 4.1.1

- cosmosdb/Ballerina.toml
- cosmosdb/Package.md
- gradle.properties
$title.
Related Pull Requests (remove if not relevant)
- Pull request 1
- Pull request 2
- One line describing the feature/improvement/fix made by this PR 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
* Ballerina Version:
* Operating System:
* Java SDK:
> Update with `graalvmCompatible` property

- native/build.gradle
The tests are currently failing due to a misconfiguration of the native JAR, which is addressed with this PR.
> Fix failing tests

- gradle.properties
$subject with bumping the version of azure cosmos. 
Related to https://github.com/ballerina-platform/ballerina-extended-library/issues/549
- Ballerina Version: 2201.7.0
- Operating System: macOS 13.4.1
- Java SDK: openjdk 11.0.20
> Fix vulnerable java dependencies 

- native/src/main/resources/META-INF/native-image/org.ballerinax/azure-cosmosdb-native/reflect-config.json
- native/src/main/resources/META-INF/native-image/org.ballerinax/azure-cosmosdb-native/resource-config.json
> $Subject
GraalVM Check is passing with these changes. [See the workflow run](https://github.com/ballerina-platform/module-ballerinax-azure-cosmosdb/actions/runs/6035008382/job/16374502703).
> Add GraalVM support

- .github/workflows/ci.yml
$subject to reduce the cost of running tests (cost is based on usage). Tests should run only during the weekly build and `push` events to the main + patch branches.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
* Ballerina Version:
* Operating System:
* Java SDK:
> Disable tests in daily build workflow

- .github/workflows/dev-stg-release.yml
- .github/workflows/release.yml
> Remove scanning of example JARs in the release workflow to avoid Trivy failure 
